<?php
/**
 * Bolt magento2 plugin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Bolt
 * @package    Bolt_Boltpay
 *
 * @copyright  Copyright (c) 2017-2021 Bolt Financial, Inc (https://www.bolt.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * Bolt Account button
 *
 * @var \Bolt\Boltpay\Block\Js $block
 */
if ($block->shouldDisableBoltCheckout()) {
    return;
}
if (!$block->isBoltSSOEnabled()) {
    return;
}

$accountJsUrl = $block->getAccountJsUrl();
$checkoutKey = $block->getCheckoutKey();
?>
<style>
    .bolt-account-sso {
        display: inline-block;
        margin-left: 20px;
        --bolt-account-sso-color: white;
    }
    .bolt-account-sso button {
        border: none !important;
        box-shadow: none !important;
        background: none !important;
    }
</style>
<div class="bolt-account-sso" data-logged-in="<?= $block->isLoggedIn() ? 'true' : 'false'; ?>"></div>
<script>
    require([
        'jquery',
        'matchMedia',
    ], function ($, mediaCheck) {
        let scriptTag = document.getElementById('bolt-account');
        if (!scriptTag) {
            scriptTag = document.createElement('script');
            scriptTag.setAttribute('type', 'text/javascript');
            scriptTag.setAttribute('async', '');
            scriptTag.setAttribute('src', '<?= /* @noEscape */ $accountJsUrl; ?>');
            scriptTag.setAttribute('id', 'bolt-account');
            scriptTag.setAttribute('data-publishable-key', '<?= /* @noEscape */ $checkoutKey; ?>');
            document.head.appendChild(scriptTag);
        }

        let injectButtonsWhenScriptLoaded = function() {
            if (typeof BoltAccount === 'undefined') {
                window.setTimeout(insertButton, 100);
                return;
            }

            BoltAccount.injectButtons();
        }

        mediaCheck({
            media: '(max-width: 768px)',
            entry: function () {
                // When magento constructs mobile menu it copies elements instead of moving
                // We need to wait for this copying, remove first bolt-account-login div
                // And only ofter that insert account.js script
                let ATTEMPT_LIMIT = 3;
                let attempts = 0;
                let timerId = setTimeout(function boltAccountLookup() {
                    let $account_div = $("div.bolt-account-login");
                    if ($account_div.length === 2) {
                        $account_div.eq(0).remove();
                        injectButtonsWhenScriptLoaded();
                    } else {
                        if(attempts === ATTEMPT_LIMIT){
                            return injectButtonsWhenScriptLoaded();
                        }
                        attempts ++;
                        timerId = setTimeout(boltAccountLookup, 1000)
                    }
                }, 100);
            },
            exit: function () {
                // For desktop we are ready to inject the buttons immediately since there is no copying happening
                injectButtonsWhenScriptLoaded();
            }
        });
    });
</script>
