<?php
/**
 * Bolt magento2 plugin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Bolt
 * @package    Bolt_Boltpay
 * @copyright  Copyright (c) 2017-2020 Bolt Financial, Inc (https://www.bolt.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * Bolt Account button
 *
 * @var $block \Bolt\Boltpay\Block\Js
 */
if ($block->shouldDisableBoltCheckout()) {
    return;
}
if (!$block->isOrderManagementEnabled()) {
    return;
}
// If CSS selector is set we want to insert button via fronend after this selector.
if ($block->getOrderManagementSelector()) {
    return;
}
if ($block->isBlockAlreadyShown('account')) {
    return;
}
$accountJsUrl = $block->getAccountJsUrl();
$checkoutKey = $block->getCheckoutKey();
?>
<div class="bolt-account-login"></div>
<script>
    require([
        'jquery',
        'matchMedia',
    ], function ($, mediaCheck) {
        var insertAccountScript = function () {
            var scriptTag = document.getElementById('bolt-account');
            if (scriptTag) {
                return;
            }
            scriptTag = document.createElement('script');
            scriptTag.setAttribute('type', 'text/javascript');
            scriptTag.setAttribute('async', '');
            scriptTag.setAttribute('src', '<?= /* @noEscape */ $accountJsUrl; ?>');
            scriptTag.setAttribute('id', 'bolt-account');
            scriptTag.setAttribute('data-publishable-key', '<?= /* @noEscape */ $checkoutKey; ?>');
            document.head.appendChild(scriptTag);
        }
        mediaCheck({
            media: '(max-width: 768px)',
            entry: function () {
                // When magento constructs mobile menu it copies elements instead of moving
                // We need to wait for this coping, remove first bolt-account-login div
                // And only ofter that insert account.js script
                var timerId = setTimeout(function boltAccountLookup() {
                    var $account_div = $("div.bolt-account-login");
                    if ($account_div.length==2) {
                        $account_div.eq(0).remove();
                        insertAccountScript();
                    } else {
                        timerId = setTimeout(boltAccountLookup, 1000)
                    }
                }, 1000);
            },
            exit: function () {
                // For desktop we are ready to insert script
                insertAccountScript();
            }
        });

    });
</script>