<?php
/**
 * Bolt magento2 plugin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Bolt
 * @package    Bolt_Boltpay
 * @copyright  Copyright (c) 2017-2023 Bolt Financial, Inc (https://www.bolt.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/**
 * Bolt Account button
 *
 * @var $block \Bolt\Boltpay\Block\Js
 * @var $secureRenderer \Magento\Framework\View\Helper\SecureHtmlRenderer
 */
if ($block->shouldDisableBoltCheckout()) {
    return;
}
if (!$block->isOrderManagementEnabled()) {
    return;
}
// If CSS selector is set we want to insert button via frontend after this selector.
if ($block->getOrderManagementSelector()) {
    return;
}
if ($block->isBlockAlreadyShown('account')) {
    return;
}
$accountJsUrl = $block->getAccountJsUrl();
$checkoutKey = $block->getCheckoutKey();
?>
<div class="bolt-account-login"></div>
<script type="text/x-magento-init">
    {
        "*": {
            "Bolt_Boltpay/js/view/account": {
                "accountJsUrl": "<?= $accountJsUrl ?>",
                "checkoutKey": "<?= $checkoutKey ?>",
                "boltSsoQueryParam": "<?= $block::BOLT_SSO_QUERY_PARAM ?>"
            }
        }
    }
</script>
