<?php
/**
 * Bolt magento2 plugin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Bolt
 * @package    Bolt_Boltpay
 * @copyright  Copyright (c) 2018 Bolt Financial, Inc (https://www.bolt.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * Bolt Account button
 *
 * @var $block \Bolt\Boltpay\Block\Js
 */
if ($block->shouldDisableBoltCheckout()) return;
if (!$block->isOrderManagementEnabled()) return;
if ($block->isBlockAlreadyShown('account')) return;
$accountJsUrl   = $block->getAccountJsUrl();
$checkoutKey  = $block->getCheckoutKey();
?>
<div class="bolt-account-login"></div>
<script
        id="bolt-account"
        type="text/javascript"
        src="<?php echo $accountJsUrl; ?>"
        data-shopping-cart-id="magento2"
        async
        data-publishable-key="<?php echo $checkoutKey; ?>">
</script>
<style>
.bolt-account-login{
    display: inline-block;
    margin-left: 15px;
}
.header.panel>.header.links{
    height: 50px;
    line-height: 50px;
}
.header.panel>.header.links>li.welcome,.header.panel>.header.links>li>a {
    line-height: 50px!important;
}
.header.panel>.header.links>li.customer-welcome>span>button {
    margin-top: 14px;
}
.header.panel {
    padding-top: 0px!important;
    padding-bottom: 0px!important;
}
</style>
