<?php
/**
 * Bolt magento2 plugin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Bolt
 * @package    Bolt_Boltpay
 * @copyright  Copyright (c) 2017-2020 Bolt Financial, Inc (https://www.bolt.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * Shopping Cart page Bolt Checkout button
 *
 * @var $block \Bolt\Boltpay\Block\Js
 */
if ($block->shouldDisableBoltCheckout()) { return;
}
$checkoutButtonUrl = $block->getCheckoutCdnUrl(). '/v1/checkout_button?publishable_key='. $block->getCheckoutKey();
$additionalCheckoutButtonClass = $block->getAdditionalCheckoutButtonClass();
$additionalCheckoutButtonAttributes = '';
foreach($block->getAdditionalCheckoutButtonAttributes() as $attrName => $attrValue) {
    $additionalCheckoutButtonAttributes .= $block->escapeHtmlAttr($attrName) . '="' . $block->escapeHtmlAttr($attrValue) . '" ';
}

?>
<?php if (!$block->isInstantCheckoutButton()) { ?>
    <div class="bolt-checkout-button bolt-multi-step-checkout <?= /* @noEscape */ $additionalCheckoutButtonClass; ?>"
         style="<?= /* @noEscape */$block->getButtonCssStyles(); ?>" <?= /* @noEscape */ $additionalCheckoutButtonAttributes; ?>>
    </div>
<?php } else { ?>
    <div data-tid="instant-bolt-checkout-button">
        <object data="<?= /* @noEscape */ $checkoutButtonUrl;?>">
        </object>
    </div>
<?php } ?>