<?php
/**
 * Bolt magento2 plugin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Bolt
 * @package    Bolt_Boltpay
 * @copyright  Copyright (c) 2017-2020 Bolt Financial, Inc (https://www.bolt.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * Bolt error message popup
 *
 * @var $block \Bolt\Boltpay\Block\Js
 */
if ($block->shouldDisableBoltCheckout()) { return;
}
?>
<div id="bolt-modal" style="display:none;">
    <div class="bolt-modal-content" data-role="content"></div>
</div>
<style>
.bolt-error-modal {
    z-index: 99999;
}
.bolt-error-modal .bolt-modal-title {
    margin-bottom: 15px;
    font-size: 16px;
}
.bolt-error-modal .bolt-modal-title span {
    font-weight: bold;
}
.bolt-error-modal .modal-footer {
    border-top: none;
}
.bolt-error-modal .modal-inner-wrap {
    border-radius: 10px;
}
</style>
<script>
var boltErrorPopup;
require(
    [
        'jquery',
        'Magento_Ui/js/modal/modal'
    ],
    function($, modal) {
        var options = {
            type: 'popup',
            responsive: true,
            innerScroll: true,
            modalClass: 'bolt-error-modal',
            title: '',
            buttons: [{
                text: $.mage.__('Close'),
                class: 'bolt-error-close-button',
                click: function () {
                    this.closeModal();
                }
            }]
        };

        boltErrorPopup = modal(options, $('#bolt-modal'));
    }
);
</script>
