#VARIABLES
m2Version="master"
magentoVersion="2.3.0"
boltApiKey=""
boltSigningSecret=""
boltPublishableKey=""
ngrokUrlHTTP="https://m2.name.dev.bolt.me/"
ngrokUrlHTTPS="https://m2.name.dev.bolt.me/"
installSampleData=true
