version: '2'
services:
  m2: 
    image: boltdev/m2-installed-plugin-ci-php72:2.3.0-v2
    container_name: m2_php
    restart: always
    tty: true
    volumes:
      - .:/home/circleci/launch
      - ..:/home/circleci/project
    ports:
    - 80:80