<?php
/**
 * Bolt magento2 plugin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Bolt
 * @package    Bolt_Boltpay
 * @copyright  Copyright (c) 2017-2020 Bolt Financial, Inc (https://www.bolt.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * Track and Connect js template
 *
 * @var $block \Bolt\Boltpay\Block\Js
 */
if ($block->shouldDisableBoltCheckout()) {
    return;
}
//check if we need Bolt on this page
if (!$block->isOnPageFromWhiteList() && !$block->isMinicartEnabled() && !$block->isBoltProductPage()) {
    return;
}

$trackJsUrl = $block->getTrackJsUrl();
$connectJsUrl = $block->getConnectJsUrl();
$checkoutKey = $block->getCheckoutKey();
?>
<script>console.log("Bolt M2 Version: <?= /* @noEscape */ $block->getModuleVersion()?>");</script>
<script
        id="bolt-track"
        type="text/javascript"
        src="<?= /* @noEscape */
        $trackJsUrl; ?>"
        data-shopping-cart-id="magento2"
        async
        data-publishable-key="<?= /* @noEscape */
        $checkoutKey; ?>">
</script>
<script
        id="bolt-connect"
        type="text/javascript"
        src="<?= /* @noEscape */
        $connectJsUrl; ?>"
        data-shopping-cart-id="magento2"
        async
        data-publishable-key="<?= /* @noEscape */
        $checkoutKey; ?>">
</script>
