<?php
/**
 * Bolt magento2 plugin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Bolt
 * @package    Bolt_Boltpay
 * @copyright  Copyright (c) 2018 Bolt Financial, Inc (https://www.bolt.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * Track js template
 *
 * @var $block \Bolt\Boltpay\Block\Js
 */

//Get track js url
if (!$block->isEnabled()) return;
$trackJsUrl   = $block->getTrackJsUrl();
$connectJsUrl = $block->getConnectJsUrl();
$checkoutKey  = $block->getCheckoutKey();
?>
<script
    id="bolt-track"
    type="text/javascript"
    src="<?php echo $trackJsUrl; ?>"
    async
    data-publishable-key="<?php echo $checkoutKey; ?>">
</script>
<script
    id="bolt-connect"
    type="text/javascript"
    src="<?php echo $connectJsUrl; ?>"
    async
    data-publishable-key="<?php echo $checkoutKey; ?>">
</script>
