<?php
/**
 * Bolt magento2 plugin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Bolt
 * @package    Bolt_Boltpay
 * @copyright  Copyright (c) 2024 Bolt Financial, Inc (https://www.bolt.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * Replace js template
 * Puts / replaces the checkout buttons according to defined selectors.
 * Maintains Bolt checkout functionality.
 *
 * @var $block \Bolt\Boltpay\Block\MinifiedJs
 * @var $secureRenderer \Magento\Framework\View\Helper\SecureHtmlRenderer
 */
if ($block->shouldDisableBoltCheckout()) { return;
}
?>

<?php $scriptString = <<<script
    ////////////////////////////////////////////////////////////////////////
    // Wait for an object to be defined and
    // execute a callback when it becomes available
    ////////////////////////////////////////////////////////////////////////
    require(['Bolt_Boltpay/js/utils/when-defined'], function (whenDefined) {
        window['whenDefined'] = whenDefined;
    });

    {$block->getGlobalJS()}

script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', ['type' => 'text/javascript'], $scriptString, false) ?>
<?php
//check if we need Bolt on this page
if (!$block->isOnPageFromWhiteList() && !$block->isMinicartEnabled() && !$block->isBoltProductPage()) { return;
}

$trackCallbackCode = $block->getTrackCallbacks();
$onShippingDetailsCompleteCode = $trackCallbackCode['shipping_details_complete'];
$onShippingOptionsCompleteCode = $trackCallbackCode['shipping_options_complete'];
$onSuccessCode = $block->getJavascriptSuccess() . $trackCallbackCode['success'];
?>

<?php $scriptString = <<<script

    // Store the configuration parameters passed from the php block
    // in the global object. Used in this file and on the payment page in payment method renderer,
    // vendor/boltpay/bolt-magento2/view/frontend/web/js/view/payment/method-renderer/boltpay.js
    window.boltConfig = {$block->getSettings()}

    window.boltConfig.trackCallbacks = {
        onCheckoutStart: {$block->wrapWithCatch($trackCallbackCode['checkout_start'])},
        onEmailEnter: {$block->wrapWithCatch($trackCallbackCode['email_enter'], 'email')},
        onShippingDetailsComplete: {$block->wrapWithCatch($onShippingDetailsCompleteCode, 'address')},
        onShippingOptionsComplete: {$block->wrapWithCatch($onShippingOptionsCompleteCode)},
        onPaymentSubmit: {$block->wrapWithCatch($trackCallbackCode['payment_submit'])},
        onSuccess: {$block->wrapWithCatch($onSuccessCode, 'data')},
        onClose: {$block->wrapWithCatch($trackCallbackCode['close'])},
    };

script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', ['type' => 'text/javascript'], $scriptString, false) ?>
<?= $block->getAdditionalHtml() ?>
