<?php
/**
 * Bolt magento2 plugin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Bolt
 * @package    Bolt_Boltpay
 * @copyright  Copyright (c) 2017-2022 Bolt Financial, Inc (https://www.bolt.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * Track, OpenReplay and Connect js template
 *
 * @var $block \Bolt\Boltpay\Block\Js
 */
if ($block->shouldDisableBoltCheckout()) {
    return;
}
?>
<script>console.log("Bolt M2 Version: <?= /* @noEscape */ $block->getModuleVersion()?>");</script>
<?php
$checkoutKey = $block->getCheckoutKey();
$isLoadConnectJs = $block->isLoadConnectJs();
$isLoadBoltJs = $block->isOnPageFromWhiteList() || $block->isMinicartEnabled() || $block->isBoltProductPage();
$isDisableTrackJs = ($block->isDisableTrackJsOnHomePage() && $block->isOnHomePage())
                    || ($block->isDisableTrackJsOnNonBoltPages() && (!$isLoadBoltJs || !$isLoadConnectJs));
$isLoadAccountJs = ($block->isBoltSSOEnabled() || $block->isOrderManagementEnabled());
$isDisableOpenReplayJs = $block->isDisableOpenReplayJs();
$isShopperAssistantEnabledJs = $block->isShopperAssistantEnabled();

if (!$isDisableTrackJs) {
    $trackJsUrl = $block->getTrackJsUrl();
?>
<script
        id="bolt-track"
        type="text/javascript"
        src="<?= /* @noEscape */
        $trackJsUrl; ?>"
        data-shopping-cart-id="magento2"
        defer
        data-publishable-key="<?= /* @noEscape */
        $checkoutKey; ?>">
</script>

<?php
}
if (!$isDisableOpenReplayJs) {
    $openReplayJsUrl = $block->getOpenReplayJsUrl();
?>
<script
        id="bolt-openreplay"
        type="text/javascript"
        src="<?= /* @noEscape */
        $openReplayJsUrl; ?>"
        data-shopping-cart-id="magento2"
        async
        data-publishable-key="<?= /* @noEscape */
        $checkoutKey; ?>">
</script>
<?php
}
if ($isLoadBoltJs && $isLoadConnectJs) {
    $connectJsUrl = $block->getConnectJsUrl();
?>
<script
        id="bolt-connect"
        type="text/javascript"
        src="<?= /* @noEscape */
        $connectJsUrl; ?>"
        data-shopping-cart-id="magento2"
        async
        data-publishable-key="<?= /* @noEscape */
        $checkoutKey; ?>">
</script>
    <?php
}
?>
<?php if ($isLoadAccountJs): ?>
    <script
        id="bolt-account"
        type="text/javascript"
        src="<?= /* @noEscape */ $block->getAccountJsUrl(); ?>"
        async
        data-publishable-key="<?= /* @noEscape */ $checkoutKey; ?>">
    </script>
<?php endif; ?>
<?php if ($isShopperAssistantEnabledJs): ?>
    <script
        id="bolt-shopper-widget"
        type="text/javascript"
        src="<?= /* @noEscape */ $block->getShopperWidgetJsUrl(); ?>"
        async
        data-publishable-key="<?= /* @noEscape */ $checkoutKey; ?>">
    </script>
<?php endif; ?>
