<?php
/**
 * Bolt magento2 plugin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Bolt
 * @package    Bolt_Boltpay
 * @copyright  Copyright (c) 2017-2023 Bolt Financial, Inc (https://www.bolt.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * Track and Connect js template
 *
 * @var \Bolt\Boltpay\Block\Js $block
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
if ($block->shouldDisableBoltCheckout()) {
    return;
}

if (!$block->isBoltSSOEnabled()) {
    return;
}

if (!$block->featureSwitches->isInitializeBoltCustomSsoButtons()) {
    return;
}

$customSSOSelectors = json_encode($block->getCustomSSOSelectors());
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Bolt_Boltpay/js/view/custom-sso-buttons": {
                "selectors": <?= $customSSOSelectors ?>
            }
        }
    }
</script>
