<?php
/**
 * Bolt magento2 plugin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Bolt
 * @package    Bolt_Boltpay
 * @copyright  Copyright (c) 2017-2023 Bolt Financial, Inc (https://www.bolt.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/**
 * @var \Bolt\Boltpay\Block\MinifiedJsCartApiDriven $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php $scriptString = <<<script
    {
        "*": {
            "Bolt_Boltpay/js/bolt-api-driven-checkout":{
                "boltConfig": {}
            }
        }
    }
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', ['type' => 'text/x-magento-init'], $scriptString, false) ?>
<?php if ($block->displayRewardPointsInMinicartConfig()): ?>
<?php $scriptString = <<<script
    require.config({
        config: {
            mixins: {
                'Magento_Reward/js/view/payment/reward': {
                    'Bolt_Boltpay/js/mixins/payment/reward': true
                }
            }
        }
    });
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
<?php endif; ?>
