<?php
/**
 * Bolt magento2 plugin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Bolt
 * @package    Bolt_Boltpay
 * @copyright  Copyright (c) 2018 Bolt Financial, Inc (https://www.bolt.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * Track and Connect js template
 *
 * @var $block \Bolt\Boltpay\Block\Js
 */
if ($block->shouldDisableBoltCheckout()) return;
//check if we need Bolt on this page
if (!$block->isOnPageFromWhiteList() && !$block->isMinicartEnabled() && !$block->isBoltProductPage()) return;

$trackJsUrl   = $block->getTrackJsUrl();
$checkoutKey  = $block->getCheckoutKey();
?>
<script>
    console.log("Bolt M2 Version: <?=$this->getModuleVersion()?>");
    // Wait for an object to be defined and execute a callback when it is
    ! function() {
        window.whenDefined = function(obj, property, callback) {
            var prop = '_'+property;
            if (obj[property]) {
                callback();
            } else {
                Object.defineProperty(obj, property, {
                    configurable: true,
                    enumerable: true,
                    writeable: true,
                    get: function() {
                        return this[prop];
                    },
                    set: function(value) {
                        this[prop] = value;
                        callback();
                    }
                });
            }
        };
    }();
    // prevent checkout opening until the main javascript loads and reconfigures it
    whenDefined(window, 'BoltCheckout', function(){
        BoltCheckout.configure(null, null, {check: function(){return false;}});
    });
</script>
<script
    id="bolt-track"
    type="text/javascript"
    src="<?php echo $trackJsUrl; ?>"
    data-shopping-cart-id="magento2"
    async
    data-publishable-key="<?php echo $checkoutKey; ?>">
</script>
