<?php
/**
 * Copyright © 2013-2017 Bolt, Inc. All rights reserved.
 * See COPYING.txt for license details.
 *
 * Track js template
 *
 * @var $block \Bolt\Boltpay\Block\Js
 */
//Get track js url
if (!$block->isEnabled()) return;
$trackJsUrl  = $block->getTrackJsUrl();
$checkoutKey = $block->getCheckoutKey();
?>
<script
  id="bolt-track"
  type="text/javascript"
  src="<?php echo $trackJsUrl; ?>"
  data-publishable-key="<?php echo $checkoutKey; ?>">
</script>
