# Number of days of inactivity before an issue becomes stale
daysUntilStale: 5
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 2
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
  - dependencies
# Label to use when marking an issue as stale
staleLabel: old
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This PR hasn't been touched in a while. Marking it as stale. If there is no
  activity in two days this PR will be auto-closed.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false