<?php
/**
 * @var \Bolt\Boltpay\Block\Form $block
 */
$code = $block->escapeHtml($block->getMethodCode());
?>

<fieldset class="admin__fieldset payment-method" id="payment_form_<?php /* @noEscape */ echo $code; ?>" style="display:none">
    <input type="hidden" id="bolt-billing-address" value='<?php echo $block->getBillingAddress() ?>' />
    <input type="hidden" id="bolt-place-order-payload" value='<?php echo $block->getPlaceOrderPayload() ?>' />
    <div class="bolt-checkout-button with-cards"></div>
    <input type="hidden" class="required-entry">
</fieldset>
