<?php
/**
 * Bolt magento2 plugin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Bolt
 * @package    Bolt_Boltpay
 * @copyright  Copyright (c) 2017-2020 Bolt Financial, Inc (https://www.bolt.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/** @var  $block \Bolt\Boltpay\Block\Customer\CreditCard */

if ($block->shouldDisableBoltCheckout()) { return;
}
$creditCards = $block->getCreditCardCollection();
?>
<div class="block">
    <div class="block-content">
        <div class="table-wrapper">
            <table  class="data table">
                <thead>
                <tr>
                    <th scope="col" class="col transaction">
                        <?= /* @noEscape */ __('Credit Card Id'); ?>
                    </th>
                    <th scope="col" class="col transaction">
                        <?= /* @noEscape */ __('Credit Card Type'); ?>
                    </th>
                    <th scope="col" class="col transaction">
                        <?= /* @noEscape */ __('Credit Card Last 4 Digit'); ?>
                    </th>
                    <th scope="col" class="col transaction">
                        <?= /* @noEscape */ __('Action'); ?>
                    </th>
                </tr>
                </thead>
                <tbody>
                <?php if (!empty($creditCards)): ?>
                    <?php foreach ($creditCards as $creditCard): ?>
                        <tr>
                            <td data-th="<?= /* @noEscape */ $block->escapeHtml(__('Credit Card ID')); ?>"
                                class="col actions">
                                <?= /* @noEscape */ $creditCard->getCreditCardId(); ?>
                            </td>
                            <td data-th="<?= /* @noEscape */ $block->escapeHtml(__('Credit Card Type')); ?>"
                                class="col actions">
                                <?= /* @noEscape */ $creditCard->getCardType(); ?>
                            </td>
                            <td data-th="<?= /* @noEscape */ $block->escapeHtml(__('Credit Card Last 4 Digit')); ?>"
                                class="col actions">
                                <?= /* @noEscape */ $creditCard->getCardLast4Digit(); ?>
                            </td>
                            <td data-th="<?= /* @noEscape */ $block->escapeHtml(__('Delete')); ?>" class="col actions">
                               <a id="remove_bolt_credit_card"
                                  href="<?= /* @noEscape */ $block->getUrl('boltpay/customer/deletecreditcard', [
                                    'id'=> $creditCard->getId(),
                                    'form_key'=> $block->getFormKey()
                               ]) ?>">
                                <?= /* @noEscape */ __('Delete') ?>
                               </a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
    <?= /* @noEscape */ $block->getPagerHtml(); ?>
</div>
<script type="text/javascript">
    require([
        'jquery',
        'Magento_Ui/js/modal/confirm'
    ], function ($, confirm) {
        $('#remove_bolt_credit_card').on("click", function (event) {
            event.stopPropagation();
            event.preventDefault();
            var url = $(this).attr('href');
            confirm({
                content: '<?= /** @noEscape */ __('Are you sure you want to delete this Bolt credit card?') ?>',
                actions: {
                    confirm: function () {
                        window.location = url;
                    },
                    cancel: function () {
                        return false;
                    }
                }
            });
        });
    });
</script>