<?php
/**
 * Bolt magento2 plugin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Bolt
 * @package    Bolt_Boltpay
 *
 * @copyright  Copyright (c) 2017-2023 Bolt Financial, Inc (https://www.bolt.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * Bolt Account button
 *
 * @var \Bolt\Boltpay\Block\Js $block
 */
if ($block->shouldDisableBoltCheckout()) {
    return;
}
if (!$block->isBoltSSOEnabled()) {
    return;
}

?>
<div class="bolt-account-sso" data-logged-in="<?= $block->isLoggedIn() ? 'true' : 'false'; ?>"></div>
