<?php
/**
 * Bolt magento2 plugin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Bolt
 * @package    Bolt_Boltpay
 * @copyright  Copyright (c) 2017-2023 Bolt Financial, Inc (https://www.bolt.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * Open Magento admin Bolt transaction link in a new tab workaround.
 * -- setting anchor target attribute is not an option because Magento removes all the attributes --
 *
 * @var $block \Bolt\Boltpay\Block\Js
 * @var $secureRenderer \Magento\Framework\View\Helper\SecureHtmlRenderer
 */
if (!$block->isEnabled()) { return;
}
?>

<?php $scriptString = <<<script

    require([
        'jquery'
    ], function ($) {
        $("body").on("click", "a[href*='.bolt.com/transaction/']", function(event) {
            event.preventDefault();
            event.stopPropagation();
            window.open(this.href, '_blank');
        });
    });

script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', ['type' => 'text/javascript'], $scriptString, false) ?>