<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var Bolt\Boltpay\Block\System\Config\Button $block
 * @see Bolt\Boltpay\Block\System\Config\Button
 */

$integrationStatus = $block->getIntegrationStatus();
?>

<script>
    require([
        'jquery',
        'prototype'
    ], function(jQuery){
        var collectSpan = jQuery('#bolt_integration_keys_span');
        var keysValueId = jQuery('#<?= trim($block->getInputId()) ?>');
        jQuery('#bolt_integration_token_button').click(function () {                      
            new Ajax.Request('<?= $block->escapeUrl($block->getProcessIntegrationTokenAjaxUrl()) ?>', {
                parameters:   {'store_id': '<?= trim($block->getStoreId()) ?>'},
                loaderArea:   false,
                asynchronous: true,
                onCreate: function() {
                    collectSpan.find('.created').hide();
                    collectSpan.find('.processing').show();
                    collectSpan.find('.failure').hide();
                    jQuery('#bolt_integration_keys_message_span').text('');
                },
                onSuccess: function(response) {
                    collectSpan.find('.processing').hide(); 
                    if (response.hasOwnProperty('responseJSON')
                        && response.responseJSON.hasOwnProperty('status')
                        && response.responseJSON.hasOwnProperty('integration_mode')
                        && response.responseJSON.hasOwnProperty('integration_status')
                        && response.responseJSON.status === 'success') {
                        jQuery('#bolt_integration_exits_proper').show();
                        jQuery('#bolt_integration_not_exist_msg').hide();
                        jQuery('#bolt_integration_exits_improper').hide();
                        collectSpan.find('.created').show();
                        collectSpan.find('.failure').hide();
                        keysValueId.val(response.responseJSON.integration_mode);
                        if (response.responseJSON.hasOwnProperty('reload')) {
                            jQuery('#bolt_integration_token_button').hide();
                            jQuery('#bolt_integration_keys_message_span').html('Success. Reloading...');
                            window.location.href = response.responseJSON.reload;
                        } else {
                            jQuery('#bolt_integration_keys_message_span').html('Success.');
                            if (response.responseJSON.integration_status == '0') {
                                jQuery('#bolt_integration_token_button span').text('Create and send API keys to Bolt');
                            } else if (response.responseJSON.integration_status == '1') {
                                jQuery('#bolt_integration_token_button span').text('Re-send API keys to Bolt');
                            } 
                        }
                    } else {
                        if (response.hasOwnProperty('responseJSON') && response.responseJSON.hasOwnProperty('errorMessage')) {
                            jQuery('#bolt_integration_keys_message_span').text(response.responseJSON.errorMessage);
                        } else {
                            jQuery('#bolt_integration_keys_message_span').text('Fail, please try again.');
                        }
                        collectSpan.find('.failure').show();
                    }
                },
                onFailure: function() {
                    collectSpan.find('.processing').hide();
                    jQuery('#bolt_integration_keys_message_span').text('Fail, please try again.');
                    collectSpan.find('.failure').show();
                }
            });
        });
    });
</script>
<span id="bolt_integration_keys_span">
    <img class="processing" hidden="hidden" alt="Processing" style="margin:0 5px" src="<?php echo $block->getViewFileUrl('images/process_spinner.gif') ?>"/>
    <img class="created" hidden="hidden" alt="Created" style="margin:-3px 5px" src="<?php echo $block->getViewFileUrl('images/rule_component_apply.gif') ?>"/>
    <img class="failure" hidden="hidden" alt="failure" style="margin:-3px 5px" src="<?php echo $block->getViewFileUrl('images/rule_component_remove.gif') ?>"/>
    <span id="bolt_integration_keys_message_span"></span>
</span>
<div class="message message-notice" id="bolt_integration_exits_proper" <?= $integrationStatus !== '1' ? 'hidden="hidden"' : '' ?>>
    <div>It looks like Magento API keys successfully sent to Bolt. If you need to send keys again please click button above.
    </div>
</div>
<div class="message message-notice" id="bolt_integration_exits_improper" <?= $integrationStatus !== '2' ? 'hidden="hidden"' : '' ?>>
    <div>It looks like Magento API keys were created for <?= trim($block->getBoltOppositeMode()) ?> and now this store is in <?= trim($block->getBoltCurrentMode()) ?> mode.
    Please delete keys and generate them again.
    </div>
</div>
