<?php
/**
 * Bolt magento2 plugin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Bolt
 * @package    Bolt_Boltpay
 * @copyright  Copyright (c) 2017-2021 Bolt Financial, Inc (https://www.bolt.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/** @var \Magento\Sales\Block\Adminhtml\Order\AbstractOrder $block */

use Bolt\Boltpay\Model\Payment;

$order = $block->getOrder();
/** @var \Bolt\Boltpay\ViewModel\OrderComment $orderCommentModel */
$orderCommentModel = $block->getOrderComment();
if (!$orderCommentModel->shouldDisplayForOrder($order)) {
    return;
}
?>
<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?php echo $block->escapeHtml(__('Order Comment')) ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item">
            <?php echo nl2br($block->escapeHtml($orderCommentModel->getCommentForOrder($order))); ?>
        </div>
    </div>
</section>
