<?php
/**
 * Bolt magento2 plugin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Bolt
 * @package    Bolt_Boltpay
 * @copyright  Copyright (c) 2018 Bolt Financial, Inc (https://www.bolt.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * Global CSS placeholder / template file
 *
 * @var $block \Bolt\Boltpay\Block\Js
 */
if ($block->shouldDisableBoltCheckout()) return;
?>
<style>
    /**************************************************************
     * Standard checkout Bolt payment radio and button
     * Can be overridden from Global CSS
     **************************************************************/
    .payment-method-boltpay .payment-method-title img.payment-icon {
        padding: 8px;
        border: 1px solid #cccccc;
        width:200px;
    }
    /***************************************************************/
    <?php echo $block->getGlobalCSS(); ?>
</style>
