<?php
/**
 * Bolt magento2 plugin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Bolt
 * @package    Bolt_Boltpay
 * @copyright  Copyright (c) 2017-2021 Bolt Financial, Inc (https://www.bolt.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * Global CSS placeholder / template file
 *
 * @var $block \Bolt\Boltpay\Block\Js
 */
if ($block->shouldDisableBoltCheckout()) { return;
}
?>
<style>
    <?= /* @noEscape */ $block->getGlobalCSS(); ?>
    <?php if ($block->isBoltSSOEnabled() 
              && $block->getFeatureSwitches()->isPreventSSOCustomersFromEditingAccountInformation()): ?>
        .customer-account-index .action.edit,
        .customer-account-index .action.change-password{
            display: none;
        }
        
        .customer-account-edit #change-email {
            display: none;
        }
        
        .customer-account-edit #change-email + label {
            display: none;
        }
        
        .customer-account-edit #change-password {
            display: none;
        }
        
        .customer-account-edit #change-password + label {
            display: none;
        }
        
        .customer-address-form .column.main * {
            display: none;
        }
        
        .customer-address-form .column.main:before {
            content: 'Addresses managed by Bolt';
        }
    <?php endif; ?>
</style>

