<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Payment\Block\Info $block
 * @see \Magento\Payment\Block\Info
 */
$specificInfo = $block->getSpecificInformation();
$boltProcessor = $block->getInfo()->getAdditionalInformation('processor');
if ( empty($boltProcessor) || $boltProcessor == \Bolt\Boltpay\Helper\Order::TP_VANTIV ) {
    $paymentTitle = $block->getMethod()->getConfigData('title', $block->getInfo()->getOrder()->getStoreId());
} else {
    $paymentTitle = 'Bolt-' . \Bolt\Boltpay\Helper\Order::TP_METHOD_DISPLAY[$boltProcessor];
}
?>
<?= $block->escapeHtml($paymentTitle) ?>

<?php if ($specificInfo) : ?>
    <table class="data-table admin__table-secondary">
    <?php foreach ($specificInfo as $label => $value) : ?>
        <tr>
            <th><?= $block->escapeHtml($label) ?>:</th>
            <td>
                <?= /* @noEscape */ nl2br($block->escapeHtml(implode("\n", $block->getValueAsArray($value, true)))) ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </table>
<?php endif;?>

<?= $block->getChildHtml() ?>
