<?php
/**
 * Bolt magento2 plugin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Bolt
 * @package    Bolt_Boltpay
 * @copyright  Copyright (c) 2020 Bolt Financial, Inc (https://www.bolt.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * @see \Magento\Payment\Block\Info
 * @var \Magento\Payment\Block\Info $block
 */
?>
<?= $block->escapeHtml($block->displayPaymentMethodTitle()) ?>{{pdf_row_separator}}

<?php if ($specificInfo = $block->getSpecificInformation()) : ?>
    <?php foreach ($specificInfo as $label => $value) : ?>
        <?= $block->escapeHtml($label) ?>:
        <?= $block->escapeHtml(implode(' ', $block->getValueAsArray($value))) ?>
        {{pdf_row_separator}}
    <?php endforeach; ?>
<?php endif;?>

<?= $block->escapeHtml(implode('{{pdf_row_separator}}', $block->getChildPdfAsArray())) ?>
