<?php
/** @var \Bolt\Boltpay\Block\Js $block */
/** @var \Bolt\Boltpay\ViewModel\CartDiscounts $cartDiscounts */

$cartDiscounts = $block->getViewModel();
$jsLayout = $cartDiscounts->getJsLayout();
if (!$jsLayout) {
    return;
}
?>
<div id="<?= /* @noEscape */ $cartDiscounts->getId(); ?>"
     data-bind="scope: '<?= /* @noEscape */ $cartDiscounts->getId(); ?>'"
     class="block">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#<?= /* @noEscape */ $cartDiscounts->getId(); ?>": {
                "Magento_Ui/js/core/app": <?= /* @noEscape */ $jsLayout; ?>
            }
        }
    </script>
</div>
