<?php
/**
 * Bolt magento2 plugin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Bolt
 * @package    Bolt_Boltpay
 * @copyright  Copyright (c) 2020 Bolt Financial, Inc (https://www.bolt.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/** @var $block Bolt\Boltpay\Block\Adminhtml\Order\View\Tab\Info */
$_order = $block->getOrder();
if (!$block->isBoltOrder($_order)) return;
?>
<br/>
<div class="admin__page-section-item-content">
    <table class="admin__table-secondary order-information-table">
        <tbody>
		<?php
		$bolt_processor = $_order->getPayment()->getAdditionalInformation('processor');
		if ( $bolt_processor == 'vantiv' ) {
			?>
            <tr>
                <th><?php echo __('Credit Card Type') ?></th>
                <td><?php echo strtoupper($_order->getPayment()->getCcType()); ?></td>
            </tr>
            <tr>
                <th><?php echo __('Credit Card Number') ?></th>
                <td><?php echo sprintf('xxxx-%s', $_order->getPayment()->getCcLast4()); ?>
                </td>
            </tr>
			<?php
		}
		else {
			?>
            <tr>
                <th colspan="2">Paid via <?php echo strtoupper($bolt_processor); ?></th>
            </tr>
			<?php
		}
		?>
        </tbody>
    </table>
</div>